# Generated by Django 3.2.13 on 2022-06-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_customers_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='purchase_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.customer'),
        ),
    ]
