# Generated by Django 3.2.13 on 2022-06-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220630_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='purchase_order_id',
            new_name='purchase_order',
        ),
    ]
