# Generated by Django 3.2.13 on 2022-06-30 04:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False 
    dependencies = [
        ('myapp', '0004_auto_20220630_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
